version: "3.8"

services:
  backend:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyBbrzGKSU0x1xaTtWRQeOBv7wXBM-IfNT4
      - AI_PROVIDER=gemini
      - MODEL_NAME=gemini-2.5-flash
    volumes:
      - ../backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

networks:
  default:
    name: excel-interviewer-network
