name: Deploy Excel Mock Interviewer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install frontend dependencies and build
    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # Run tests
    - name: Run tests
      run: |
        pytest tests/

    # Build Docker image
    - name: Build Docker image
      run: docker-compose build

    # Deploy (example using Azure Web Apps)
    - name: Deploy to Azure Web Apps
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'excel-interviewer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .